In [19]:
import pandas as pd

data = {
    'Customer_Name': ['Rahul Sharma', 'Priya Singh', 'Amit Kumar', 'Neha Verma', 'Rohan Mehta', 'Anjali Gupta'],
    'Gender': ['Male', 'Female', 'Male', 'Female', 'Male', 'Female'],
    'Sales': [25000, 800, 55000, 15000, 500, 40000],
    'Payment_Method': ['Credit Card', 'Cash', 'Debit Card', 'Credit Card', 'Debit Card', 'Cash'],
    'City': ['Jaipur', 'Delhi', 'Mumbai', 'Jaipur', 'Delhi', 'Mumbai']
}

df = pd.DataFrame(data)

print(df)

  Customer_Name  Gender  Sales Payment_Method    City
0  Rahul Sharma    Male  25000    Credit Card  Jaipur
1   Priya Singh  Female    800           Cash   Delhi
2    Amit Kumar    Male  55000     Debit Card  Mumbai
3    Neha Verma  Female  15000    Credit Card  Jaipur
4   Rohan Mehta    Male    500     Debit Card   Delhi
5  Anjali Gupta  Female  40000           Cash  Mumbai

In [ ]:
# apply
# df['Customer_Name_Length'] = df['Customer_Name'].apply(len)

# df['Sales_Category'] = df['Sales'].apply(
# lambda x: 'High' if x >= 20000 else 'Low'
# )


# # map
# df['Gender_Code'] = df['Gender'].map({'Male': 1, 'Female': 0})


# # replace
# df['Payment_Method'] = df['Payment_Method'].replace(
# {'Credit Card':'Card', 'Debit Card':'Card'}
# )


# TRUE → original value
# FALSE → replacement value


# where
df['Sales_Capped'] = df['Sales'].where(df['Sales'] <= 50000, 50000)


# mask
df['Sales_Adjusted'] = df['Sales'].mask(df['Sales'] < 10000, 1000)


df

,Customer_Name,Gender,Sales,Payment_Method,City,Gender_Code,Sales_Capped,Sales_Adjusted
0,Rahul Sharma,Male,25000,Credit Card,Jaipur,1,25000,25000
1,Priya Singh,Female,800,Cash,Delhi,0,800,1000
2,Amit Kumar,Male,55000,Debit Card,Mumbai,1,50000,55000
3,Neha Verma,Female,15000,Credit Card,Jaipur,0,15000,15000
4,Rohan Mehta,Male,500,Debit Card,Delhi,1,500,1000
5,Anjali Gupta,Female,40000,Cash,Mumbai,0,40000,40000

In [20]:
df['Gender_Code'] = df['Gender'].map({'Male': 1, 'Female': 0})
df

  Customer_Name  Gender  Sales Payment_Method    City  Gender_Code
0  Rahul Sharma    Male  25000    Credit Card  Jaipur            1
1   Priya Singh  Female    800           Cash   Delhi            0
2    Amit Kumar    Male  55000     Debit Card  Mumbai            1
3    Neha Verma  Female  15000    Credit Card  Jaipur            0
4   Rohan Mehta    Male    500     Debit Card   Delhi            1
5  Anjali Gupta  Female  40000           Cash  Mumbai            0

In [4]:
df['Sales_Capped'] = df['Sales'].where(df['Sales'] <= 50000, 50000)
df

  Customer_Name  Gender  Sales Payment_Method    City  Sales_Capped
0  Rahul Sharma    Male  25000    Credit Card  Jaipur         25000
1   Priya Singh  Female    800           Cash   Delhi           800
2    Amit Kumar    Male  55000     Debit Card  Mumbai         50000
3    Neha Verma  Female  15000    Credit Card  Jaipur         15000
4   Rohan Mehta    Male    500     Debit Card   Delhi           500
5  Anjali Gupta  Female  40000           Cash  Mumbai         40000

In [5]:
df['Sales_Adjusted'] = df['Sales'].mask(df['Sales'] < 1000, 1000)
df

,Customer_Name,Gender,Sales,Payment_Method,City,Sales_Capped,Sales_Adjusted
0,Rahul Sharma,Male,25000,Credit Card,Jaipur,25000,25000
1,Priya Singh,Female,800,Cash,Delhi,800,1000
2,Amit Kumar,Male,55000,Debit Card,Mumbai,50000,55000
3,Neha Verma,Female,15000,Credit Card,Jaipur,15000,15000
4,Rohan Mehta,Male,500,Debit Card,Delhi,500,1000
5,Anjali Gupta,Female,40000,Cash,Mumbai,40000,40000

In [24]:
# df.groupby('column')['col'].agg_func


import pandas as pd

data = {
    'Order_ID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'City': ['Jaipur', 'Delhi', 'Jaipur', 'Mumbai', 'Delhi',
             'Mumbai', 'Jaipur', 'Delhi', 'Mumbai', 'Jaipur'],
    'Category': ['Electronics', 'Clothing', 'Clothing', 'Electronics',
                 'Electronics', 'Clothing', 'Electronics', 'Clothing',
                 'Electronics', 'Clothing'],
    'Sales': [25000, 12000, 15000, 30000, 22000,
              18000, 28000, 10000, 35000, 14000]
}

df = pd.DataFrame(data)

# print(df)


# df.groupby('Category')['Sales'].sum()

# df.groupby('Category')['Sales'].mean()

# df.groupby('City')['Sales'].sum()

df.groupby(['City','Category'])['Sales'].sum()

City    Category
Delhi   Clothing       22000
        Electronics    22000
Jaipur  Clothing       29000
        Electronics    53000
Mumbai  Clothing       18000
        Electronics    65000
Name: Sales, dtype: int64

In [15]:
import pandas as pd

df = pd.DataFrame({
    "Category": ["A", "A", "B", "B", "C"],
    "Sales": [100, 200, 150, 250, 300],
    "Quantity": [2, 4, 3, 5, 6],
    "Profit": [20, 40, 30, 50, 60]
})


df.groupby('Category').agg({
'Sales': ['sum','mean','max'],
'Quantity': 'sum'
})

         Sales             Quantity
           sum   mean  max      sum
Category
A          300  150.0  200        6
B          400  200.0  250        8
C          300  300.0  300        6

In [17]:
summary = df.groupby('Category').agg(
Total_Sales=('Sales', 'sum'),
Average_Sales=('Sales', 'mean'),
Max_Sales=('Sales', 'max'),
Total_Quantity=('Quantity', 'sum')).reset_index()

summary

  Category  Total_Sales  Average_Sales  Max_Sales  Total_Quantity
0        A          300          150.0        200               6
1        B          400          200.0        250               8
2        C          300          300.0        300               6

In [1]:
import pandas as pd

data = {
    "Order_ID": range(1001, 1051),

    "Customer": [
        "Amit", "Priya", "Rahul", "Neha", "Vikas",
        "Sneha", "Rohit", "Anjali", "Karan", "Pooja",
        "Amit", "Priya", "Rahul", "Neha", "Vikas",
        "Sneha", "Rohit", "Anjali", "Karan", "Pooja",
        "Amit", "Priya", "Rahul", "Neha", "Vikas",
        "Sneha", "Rohit", "Anjali", "Karan", "Pooja",
        "Amit", "Priya", "Rahul", "Neha", "Vikas",
        "Sneha", "Rohit", "Anjali", "Karan", "Pooja",
        "Amit", "Priya", "Rahul", "Neha", "Vikas",
        "Sneha", "Rohit", "Anjali", "Karan", "Pooja"
    ],

    "City": [
        "Delhi", "Mumbai", "Jaipur", "Delhi", "Pune",
        "Mumbai", "Jaipur", "Delhi", "Pune", "Mumbai",
        "Delhi", "Mumbai", "Jaipur", "Delhi", "Pune",
        "Mumbai", "Jaipur", "Delhi", "Pune", "Mumbai",
        "Delhi", "Mumbai", "Jaipur", "Delhi", "Pune",
        "Mumbai", "Jaipur", "Delhi", "Pune", "Mumbai",
        "Delhi", "Mumbai", "Jaipur", "Delhi", "Pune",
        "Mumbai", "Jaipur", "Delhi", "Pune", "Mumbai",
        "Delhi", "Mumbai", "Jaipur", "Delhi", "Pune",
        "Mumbai", "Jaipur", "Delhi", "Pune", "Mumbai"
    ],

    "Category": [
        "Electronics", "Furniture", "Clothing", "Electronics", "Furniture",
        "Clothing", "Electronics", "Clothing", "Furniture", "Electronics",
        "Clothing", "Furniture", "Electronics", "Clothing", "Furniture",
        "Electronics", "Clothing", "Furniture", "Electronics", "Clothing",
        "Furniture", "Electronics", "Clothing", "Furniture", "Electronics",
        "Clothing", "Furniture", "Electronics", "Clothing", "Furniture",
        "Electronics", "Clothing", "Furniture", "Electronics", "Clothing",
        "Furniture", "Electronics", "Clothing", "Furniture", "Electronics",
        "Clothing", "Furniture", "Electronics", "Clothing", "Furniture",
        "Electronics", "Clothing", "Furniture", "Electronics", "Clothing"
    ],

    "Product": [
        "Laptop", "Chair", "T-Shirt", "Mobile", "Table",
        "Jeans", "Headphones", "Shoes", "Sofa", "Tablet",
        "Jacket", "Desk", "Laptop", "T-Shirt", "Chair",
        "Mobile", "Shoes", "Table", "Headphones", "Jeans",
        "Sofa", "Tablet", "Jacket", "Desk", "Laptop",
        "Shoes", "Chair", "Mobile", "T-Shirt", "Table",
        "Headphones", "Jeans", "Sofa", "Laptop", "Jacket",
        "Tablet", "Shoes", "Desk", "Mobile", "Chair",
        "T-Shirt", "Headphones", "Table", "Jeans", "Laptop",
        "Sofa", "Tablet", "Jacket", "Shoes", "Desk"
    ],

    "Quantity": [
        2, 1, 4, 2, 1,
        3, 2, 5, 1, 2,
        3, 2, 1, 4, 2,
        3, 5, 1, 2, 4,
        2, 3, 4, 1, 2,
        5, 2, 3, 4, 1,
        2, 3, 1, 4, 2,
        3, 5, 2, 1, 4,
        3, 2, 5, 1, 2,
        4, 3, 2, 5, 1
    ],

    "Sales": [
        1200, 800, 600, 1500, 900,
        700, 1100, 750, 1300, 1600,
        650, 1000, 1250, 700, 850,
        1400, 900, 1200, 1150, 800,
        1350, 1700, 650, 950, 1450,
        1000, 780, 1550, 720, 1100,
        1250, 850, 600, 1600, 900,
        950, 1400, 780, 1150, 1300,
        700, 1200, 1450, 820, 1050,
        1500, 900, 1350, 760, 1100
    ],

    "Profit": [
        200, 120, 150, 300, 180,
        140, 220, 160, 250, 320,
        130, 200, 250, 140, 170,
        280, 180, 240, 230, 160,
        270, 340, 130, 190, 290,
        200, 150, 310, 140, 220,
        250, 170, 120, 320, 180,
        190, 280, 150, 230, 260,
        140, 240, 290, 160, 210,
        300, 180, 270, 150, 220
    ],

    "Payment_Mode": [
        "UPI", "Card", "Cash", "UPI", "Card",
        "Cash", "UPI", "Card", "Cash", "UPI",
        "Card", "Cash", "UPI", "Card", "Cash",
        "UPI", "Card", "Cash", "UPI", "Card",
        "Cash", "UPI", "Card", "Cash", "UPI",
        "Card", "Cash", "UPI", "Card", "Cash",
        "UPI", "Card", "Cash", "UPI", "Card",
        "Cash", "UPI", "Card", "Cash", "UPI",
        "Card", "Cash", "UPI", "Card", "Cash",
        "UPI", "Card", "Cash", "UPI", "Card"
    ],

    "Order_Status": [
        "Delivered", "Delivered", "Pending", "Delivered", "Cancelled",
        "Delivered", "Pending", "Delivered", "Cancelled", "Delivered",
        "Delivered", "Pending", "Delivered", "Cancelled", "Delivered",
        "Pending", "Delivered", "Delivered", "Cancelled", "Pending",
        "Delivered", "Delivered", "Cancelled", "Pending", "Delivered",
        "Delivered", "Pending", "Delivered", "Cancelled", "Delivered",
        "Pending", "Delivered", "Cancelled", "Delivered", "Delivered",
        "Pending", "Cancelled", "Delivered", "Pending", "Delivered",
        "Delivered", "Cancelled", "Pending", "Delivered", "Delivered",
        "Pending", "Cancelled", "Delivered", "Pending", "Delivered"
    ]
}

df = pd.DataFrame(data)

print(df)

    Order_ID Customer    City     Category     Product  Quantity  Sales  \
0       1001     Amit   Delhi  Electronics      Laptop         2   1200
1       1002    Priya  Mumbai    Furniture       Chair         1    800
2       1003    Rahul  Jaipur     Clothing     T-Shirt         4    600
3       1004     Neha   Delhi  Electronics      Mobile         2   1500
4       1005    Vikas    Pune    Furniture       Table         1    900
5       1006    Sneha  Mumbai     Clothing       Jeans         3    700
6       1007    Rohit  Jaipur  Electronics  Headphones         2   1100
7       1008   Anjali   Delhi     Clothing       Shoes         5    750
8       1009    Karan    Pune    Furniture        Sofa         1   1300
9       1010    Pooja  Mumbai  Electronics      Tablet         2   1600
10      1011     Amit   Delhi     Clothing      Jacket         3    650
11      1012    Priya  Mumbai    Furniture        Desk         2   1000
12      1013    Rahul  Jaipur  Electronics      Laptop         1   1250
13      1014     Neha   Delhi     Clothing     T-Shirt         4    700
14      1015    Vikas    Pune    Furniture       Chair         2    850
15      1016    Sneha  Mumbai  Electronics      Mobile         3   1400
16      1017    Rohit  Jaipur     Clothing       Shoes         5    900
17      1018   Anjali   Delhi    Furniture       Table         1   1200
18      1019    Karan    Pune  Electronics  Headphones         2   1150
19      1020    Pooja  Mumbai     Clothing       Jeans         4    800
20      1021     Amit   Delhi    Furniture        Sofa         2   1350
21      1022    Priya  Mumbai  Electronics      Tablet         3   1700
22      1023    Rahul  Jaipur     Clothing      Jacket         4    650
23      1024     Neha   Delhi    Furniture        Desk         1    950
24      1025    Vikas    Pune  Electronics      Laptop         2   1450
25      1026    Sneha  Mumbai     Clothing       Shoes         5   1000
26      1027    Rohit  Jaipur    Furniture       Chair         2    780
27      1028   Anjali   Delhi  Electronics      Mobile         3   1550
28      1029    Karan    Pune     Clothing     T-Shirt         4    720
29      1030    Pooja  Mumbai    Furniture       Table         1   1100
30      1031     Amit   Delhi  Electronics  Headphones         2   1250
31      1032    Priya  Mumbai     Clothing       Jeans         3    850
32      1033    Rahul  Jaipur    Furniture        Sofa         1    600
33      1034     Neha   Delhi  Electronics      Laptop         4   1600
34      1035    Vikas    Pune     Clothing      Jacket         2    900
35      1036    Sneha  Mumbai    Furniture      Tablet         3    950
36      1037    Rohit  Jaipur  Electronics       Shoes         5   1400
37      1038   Anjali   Delhi     Clothing        Desk         2    780
38      1039    Karan    Pune    Furniture      Mobile         1   1150
39      1040    Pooja  Mumbai  Electronics       Chair         4   1300
40      1041     Amit   Delhi     Clothing     T-Shirt         3    700
41      1042    Priya  Mumbai    Furniture  Headphones         2   1200
42      1043    Rahul  Jaipur  Electronics       Table         5   1450
43      1044     Neha   Delhi     Clothing       Jeans         1    820
44      1045    Vikas    Pune    Furniture      Laptop         2   1050
45      1046    Sneha  Mumbai  Electronics        Sofa         4   1500
46      1047    Rohit  Jaipur     Clothing      Tablet         3    900
47      1048   Anjali   Delhi    Furniture      Jacket         2   1350
48      1049    Karan    Pune  Electronics       Shoes         5    760
49      1050    Pooja  Mumbai     Clothing        Desk         1   1100

    Profit Payment_Mode Order_Status
0      200          UPI    Delivered
1      120         Card    Delivered
2      150         Cash      Pending
3      300          UPI    Delivered
4      180         Card    Cancelled
5      140         Cash    Delivered
6      220          UPI      Pending
7      160         Card    Delivered
8      250         Cash    Cancelled
9      320          UPI    Delivered
10     130         Card    Delivered
11     200         Cash      Pending
12     250          UPI    Delivered
13     140         Card    Cancelled
14     170         Cash    Delivered
15     280          UPI      Pending
16     180         Card    Delivered
17     240         Cash    Delivered
18     230          UPI    Cancelled
19     160         Card      Pending
20     270         Cash    Delivered
21     340          UPI    Delivered
22     130         Card    Cancelled
23     190         Cash      Pending
24     290          UPI    Delivered
25     200         Card    Delivered
26     150         Cash      Pending
27     310          UPI    Delivered
28     140         Card    Cancelled
29     220         Cash    Delivered
30     250          UPI      Pending
31     170         Card    Delivered
32     120         Cash    Cancelled
33     320          UPI    Delivered
34     180         Card    Delivered
35     190         Cash      Pending
36     280          UPI    Cancelled
37     150         Card    Delivered
38     230         Cash      Pending
39     260          UPI    Delivered
40     140         Card    Delivered
41     240         Cash    Cancelled
42     290          UPI      Pending
43     160         Card    Delivered
44     210         Cash    Delivered
45     300          UPI      Pending
46     180         Card    Cancelled
47     270         Cash    Delivered
48     150          UPI      Pending
49     220         Card    Delivered

In [2]:
# Category Wise Total Sales

pd.pivot_table(
    df,
    values='Sales',
    index='Category',
    aggfunc='sum'
)

             Sales
Category
Clothing     13520
Electronics  23160
Furniture    16530

In [3]:
# City Wise Total Sales

pd.pivot_table(
    df,
    values='Sales',
    index='City',
    aggfunc='sum'
)

        Sales
City
Delhi   16350
Jaipur   9630
Mumbai  17000
Pune    10230

In [4]:
# Category & City Wise Sales
pd.pivot_table(
    df,
    values='Sales',
    index='Category',
    columns='City',
    aggfunc='sum',
    fill_value=0
)

City         Delhi  Jaipur  Mumbai  Pune
Category
Clothing      4400    3050    4450  1620
Electronics   7100    5200    7500  3360
Furniture     4850    1380    5050  5250

In [ ]:
# Category Wise Total Sales & Avg, No. of Orders
pd.pivot_table(
    df,
    values='Sales',
    index='Category',
    aggfunc=['sum', 'mean', 'count']
)

               sum         mean count
             Sales        Sales Sales
Category
Clothing     13520   795.294118    17
Electronics  23160  1362.352941    17
Furniture    16530  1033.125000    16

In [4]:
# City & Category Avg Profit
pd.pivot_table(
    df,
    values='Profit',
    index='City',
    columns='Category',
    aggfunc='mean',
    fill_value=0
)

Category    Clothing  Electronics  Furniture
City
Delhi     146.666667   276.000000      242.5
Jaipur    160.000000   260.000000      135.0
Mumbai    178.000000   300.000000      194.0
Pune      160.000000   223.333333      208.0

In [5]:
# City Wise Sales for each Payment Mode
pd.pivot_table(
    df,
    values='Sales',
    index='City',
    columns='Payment_Mode',
    aggfunc='sum'
)

Payment_Mode  Card  Cash   UPI
City
Delhi         4400  4850  7100
Jaipur        2450  1980  5200
Mumbai        4550  4950  7500
Pune          2520  4350  3360

In [6]:
# Category × Order Status
pd.pivot_table(df, values='Order_Status', 
               index='Category',
            #    columns='Order_Status', 
               aggfunc='count', 
               fill_value=0)

             Order_Status
Category
Clothing               17
Electronics            17
Furniture              16

In [27]:
df['Category_Avg'] = df.groupby('Category')['Sales'].transform('mean')


df['City_Total'] = df.groupby('City')['Sales'].transform('sum')

df

,Order_ID,Customer,City,Category,Product,Quantity,Sales,Profit,Payment_Mode,Order_Status,Category_Avg,City_Total
0,1001,Amit,Delhi,Electronics,Laptop,2,1200,200,UPI,Delivered,1362.352941,16350
1,1002,Priya,Mumbai,Furniture,Chair,1,800,120,Card,Delivered,1033.125000,17000
2,1003,Rahul,Jaipur,Clothing,T-Shirt,4,600,150,Cash,Pending,795.294118,9630
3,1004,Neha,Delhi,Electronics,Mobile,2,1500,300,UPI,Delivered,1362.352941,16350
4,1005,Vikas,Pune,Furniture,Table,1,900,180,Card,Cancelled,1033.125000,10230
5,1006,Sneha,Mumbai,Clothing,Jeans,3,700,140,Cash,Delivered,795.294118,17000
6,1007,Rohit,Jaipur,Electronics,Headphones,2,1100,220,UPI,Pending,1362.352941,9630
7,1008,Anjali,Delhi,Clothing,Shoes,5,750,160,Card,Delivered,795.294118,16350
8,1009,Karan,Pune,Furniture,Sofa,1,1300,250,Cash,Cancelled,1033.125000,10230
9,1010,Pooja,Mumbai,Electronics,Tablet,2,1600,320,UPI,Delivered,1362.352941,17000
10,1011,Amit,Delhi,Clothing,Jacket,3,650,130,Card,Delivered,795.294118,16350
11,1012,Priya,Mumbai,Furniture,Desk,2,1000,200,Cash,Pending,1033.125000,17000
12,1013,Rahul,Jaipur,Electronics,Laptop,1,1250,250,UPI,Delivered,1362.352941,9630
13,1014,Neha,Delhi,Clothing,T-Shirt,4,700,140,Card,Cancelled,795.294118,16350
14,1015,Vikas,Pune,Furniture,Chair,2,850,170,Cash,Delivered,1033.125000,10230
15,1016,Sneha,Mumbai,Electronics,Mobile,3,1400,280,UPI,Pending,1362.352941,17000
16,1017,Rohit,Jaipur,Clothing,Shoes,5,900,180,Card,Delivered,795.294118,9630
17,1018,Anjali,Delhi,Furniture,Table,1,1200,240,Cash,Delivered,1033.125000,16350
18,1019,Karan,Pune,Electronics,Headphones,2,1150,230,UPI,Cancelled,1362.352941,10230
19,1020,Pooja,Mumbai,Clothing,Jeans,4,800,160,Card,Pending,795.294118,17000
20,1021,Amit,Delhi,Furniture,Sofa,2,1350,270,Cash,Delivered,1033.125000,16350
21,1022,Priya,Mumbai,Electronics,Tablet,3,1700,340,UPI,Delivered,1362.352941,17000
22,1023,Rahul,Jaipur,Clothing,Jacket,4,650,130,Card,Cancelled,795.294118,9630
23,1024,Neha,Delhi,Furniture,Desk,1,950,190,Cash,Pending,1033.125000,16350
24,1025,Vikas,Pune,Electronics,Laptop,2,1450,290,UPI,Delivered,1362.352941,10230
25,1026,Sneha,Mumbai,Clothing,Shoes,5,1000,200,Card,Delivered,795.294118,17000
26,1027,Rohit,Jaipur,Furniture,Chair,2,780,150,Cash,Pending,1033.125000,9630
27,1028,Anjali,Delhi,Electronics,Mobile,3,1550,310,UPI,Delivered,1362.352941,16350
28,1029,Karan,Pune,Clothing,T-Shirt,4,720,140,Card,Cancelled,795.294118,10230
29,1030,Pooja,Mumbai,Furniture,Table,1,1100,220,Cash,Delivered,1033.125000,17000
30,1031,Amit,Delhi,Electronics,Headphones,2,1250,250,UPI,Pending,1362.352941,16350
31,1032,Priya,Mumbai,Clothing,Jeans,3,850,170,Card,Delivered,795.294118,17000
32,1033,Rahul,Jaipur,Furniture,Sofa,1,600,120,Cash,Cancelled,1033.125000,9630
33,1034,Neha,Delhi,Electronics,Laptop,4,1600,320,UPI,Delivered,1362.352941,16350
34,1035,Vikas,Pune,Clothing,Jacket,2,900,180,Card,Delivered,795.294118,10230
35,1036,Sneha,Mumbai,Furniture,Tablet,3,950,190,Cash,Pending,1033.125000,17000
36,1037,Rohit,Jaipur,Electronics,Shoes,5,1400,280,UPI,Cancelled,1362.352941,9630
37,1038,Anjali,Delhi,Clothing,Desk,2,780,150,Card,Delivered,795.294118,16350
38,1039,Karan,Pune,Furniture,Mobile,1,1150,230,Cash,Pending,1033.125000,10230
39,1040,Pooja,Mumbai,Electronics,Chair,4,1300,260,UPI,Delivered,1362.352941,17000
40,1041,Amit,Delhi,Clothing,T-Shirt,3,700,140,Card,Delivered,795.294118,16350
41,1042,Priya,Mumbai,Furniture,Headphones,2,1200,240,Cash,Cancelled,1033.125000,17000
42,1043,Rahul,Jaipur,Electronics,Table,5,1450,290,UPI,Pending,1362.352941,9630
43,1044,Neha,Delhi,Clothing,Jeans,1,820,160,Card,Delivered,795.294118,16350
44,1045,Vikas,Pune,Furniture,Laptop,2,1050,210,Cash,Delivered,1033.125000,10230
45,1046,Sneha,Mumbai,Electronics,Sofa,4,1500,300,UPI,Pending,1362.352941,17000
46,1047,Rohit,Jaipur,Clothing,Tablet,3,900,180,Card,Cancelled,795.294118,9630
47,1048,Anjali,Delhi,Furniture,Jacket,2,1350,270,Cash,Delivered,1033.125000,16350
48,1049,Karan,Pune,Electronics,Shoes,5,760,150,UPI,Pending,1362.352941,10230
49,1050,Pooja,Mumbai,Clothing,Desk,1,1100,220,Card,Delivered,795.294118,17000